name: Terraform Test
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.tf"
      - "**.tfvars"
      - "test/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/terraform-test.y*ml"
      - "!**.md"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          # 21600 seconds == 6 hours
          # 1800 seconds == 30 minutes
          role-duration-seconds: 1800

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run Tests
        run: make test
